name: build check 

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.1

      - name: Print go version
        run: go version

      - name: Build the binary
        run:  make build